name: stock_alert_app
description: A 股股票异动监控应用，支持实时搜索、自选、后台守护、语音播报与本地持久化。
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
